/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    checkstyle
    id("edu.sc.seis.launch4j") version "2.5.0"
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("java")
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

application {
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

tasks.getByName("run", JavaExec::class) {
    standardInput = System.`in`
}

tasks.jar {
    archiveFileName.set("myapp.jar")
}

launch4j {
    mainClassName = "org.example.App"
    outfile = "AwesomeGICBank.exe"
    headerType = "console"
    icon = "${projectDir}/icon/piggybank.ico"

}

tasks.shadowJar {
    archiveFileName.set("AwesomeGICBank.jar")
    destinationDirectory.set(file("${projectDir}/../FinalApplicationJar"))
}
